// <auto-generated />
using System;
using DriveTogetherApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveTogetherApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231227213209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresseId"));

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresseId");

                    b.ToTable("Adressen");
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Auto", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<DateTime>("Baujahr")
                        .HasColumnType("datetime2");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<string>("Farbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kennzeichen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutoId");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            AutoId = 1,
                            Baujahr = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BenutzerId = 1,
                            Farbe = "Rot",
                            Kennzeichen = "B-MK 1234",
                            Marke = "Volkswagen",
                            Modell = "Polo",
                            Typ = "SUV"
                        },
                        new
                        {
                            AutoId = 2,
                            Baujahr = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BenutzerId = 1,
                            Farbe = "Blau",
                            Kennzeichen = "B-MK 1234",
                            Marke = "Volkswagen",
                            Modell = "Golf",
                            Typ = "Limousine"
                        });
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Benutzer", b =>
                {
                    b.Property<int>("BenutzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenutzerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Geburtsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswortSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Registrierungsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenutzerId");

                    b.ToTable("Benutzers");

                    b.HasData(
                        new
                        {
                            BenutzerId = 1,
                            Email = "max.mustermann@example.com",
                            Geburtsdatum = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nachname = "Mustermann",
                            PasswortHash = new byte[0],
                            PasswortSalt = new byte[0],
                            Registrierungsdatum = new DateTime(2023, 12, 27, 22, 32, 9, 240, DateTimeKind.Local).AddTicks(384),
                            Telefonnummer = "0123456789",
                            Vorname = "Max"
                        });
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Buchung", b =>
                {
                    b.Property<int>("BuchungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuchungId"));

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Buchungsdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("FahrtId")
                        .HasColumnType("int");

                    b.Property<bool>("Storniert")
                        .HasColumnType("bit");

                    b.HasKey("BuchungId");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("FahrtId");

                    b.ToTable("Buchungen");
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Fahrt", b =>
                {
                    b.Property<int>("FahrtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FahrtId"));

                    b.Property<int>("AbfahrtAdresseId")
                        .HasColumnType("int");

                    b.Property<int>("AnkunftAdresseId")
                        .HasColumnType("int");

                    b.Property<int>("AnzahlSitzplaetze")
                        .HasColumnType("int");

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Storniert")
                        .HasColumnType("bit");

                    b.HasKey("FahrtId");

                    b.HasIndex("AbfahrtAdresseId");

                    b.HasIndex("AnkunftAdresseId");

                    b.HasIndex("AutoId");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Fahrten");
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Auto", b =>
                {
                    b.HasOne("DriveTogetherApp.Shared.Model.Benutzer", null)
                        .WithMany("Autos")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Buchung", b =>
                {
                    b.HasOne("DriveTogetherApp.Shared.Model.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveTogetherApp.Shared.Model.Fahrt", null)
                        .WithMany()
                        .HasForeignKey("FahrtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Fahrt", b =>
                {
                    b.HasOne("DriveTogetherApp.Shared.Model.Adresse", "AbfahrtAdresse")
                        .WithMany()
                        .HasForeignKey("AbfahrtAdresseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DriveTogetherApp.Shared.Model.Adresse", "AnkunftAdresse")
                        .WithMany()
                        .HasForeignKey("AnkunftAdresseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DriveTogetherApp.Shared.Model.Auto", null)
                        .WithMany()
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DriveTogetherApp.Shared.Model.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AbfahrtAdresse");

                    b.Navigation("AnkunftAdresse");
                });

            modelBuilder.Entity("DriveTogetherApp.Shared.Model.Benutzer", b =>
                {
                    b.Navigation("Autos");
                });
#pragma warning restore 612, 618
        }
    }
}
